task 07-03 index search
js-tasks-ru/nodejs-20201020_stepanenko-oleksii pull request #10
Opened 2020-11-08 18:15 UTC by PelicanDan

2020-11-08 19:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Поиск товаров
+ у модели есть текстовый индекс с именем TextSearchIndex
+ индекс должен включать поля title и description
+ индекс содержит указание весов для полей
+ язык по умолчанию - русский
+ товары должны возвращаться в поряд��е релевантности
+ если ничего не найдено - пустой массив
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-08 21:49 UTC, PelicanDan commented
Может быть надо было через find( { $text: { $search: "\"coffee shop\"" } } ) искать

2020-11-09 09:12 UTC, tadjik1 commented on 07-mongodb-mongoose/03-search/controllers/products.js
> +      ]});
текстовый поиск намного эффективнее чем использование регулярных выражений. кроме этого он еще учитывает морфологию того или иного языка. так как у нас есть текстовый индекс для коллекции товаров - то мы можем использовать специальный оператор `$text` для поиска. вот пример: https://docs.mongodb.com/manual/reference/operator/query/text/#search-for-a-single-word

2020-11-09 09:12 UTC, tadjik1 requested changes
@PelicanDan в целом правильное направление, но надо немного поправить обработку запроса - и функцию поиска документов

2020-11-09 10:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-09 10:13 UTC, tadjik1 approved these changes
да, так хорошо :) 

почитайте еще, пожалуйста, моё решение - я описал в нём еще одну интересную возможность текстового поиска - ранжирование результатов по релевантности, т.е. условно: по запросу "промисы" статья "промисы: полное руководство" должна быть выше в результатах чем "основные подходы к асинхронности".

2020-11-09 10:13 UTC, merged

2020-11-09 10:14 UTC, PelicanDan commented on 07-mongodb-mongoose/03-search/controllers/products.js
> +      ]});
@tadjik1 Спасибо за уточнение! Я немного поэкперементировал с индексами. У меня получилось только замедлить запросы, если создавать не эффективный индекс lol